"""add last_reminded_date to tasks

Revision ID: 1c41c91fb40e
Revises: 8b02e54e0b8d
Create Date: 2026-07-22 02:25:46.908226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c41c91fb40e'
down_revision: Union[str, None] = '8b02e54e0b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_reminded_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminded_date')
    # ### end Alembic commands ###
